spring:
  profiles:
    active: "local"
  application:
    name: gateway-api
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
#  sleuth:
#    sampler:
#      probability: 1.0 #trace all request
#  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
#    baseUrl: http://localhost:9411
server:
  port: 8980
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"